/*
  # Fix sira_no identity column on document_master_list

  ## Problem
  sira_no is currently defined as GENERATED ALWAYS AS IDENTITY, which prevents
  inserting any explicit value — causing the error
  "cannot insert a non-DEFAULT value into column 'sira_no'".

  ## Fix
  Change the identity generation to GENERATED BY DEFAULT AS IDENTITY.
  This allows explicit values to be provided (user-supplied sira_no),
  while still auto-incrementing when no value is given.
*/

ALTER TABLE document_master_list
  ALTER COLUMN sira_no SET GENERATED BY DEFAULT;
